# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.srcs/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m.xci
# IP: The module: 'mmcm_50m_to_400m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.gen/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m_to_400m'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.gen/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m_to_400m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.gen/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m_to_400m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.srcs/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m.xci
# IP: The module: 'mmcm_50m_to_400m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.gen/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m_to_400m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.gen/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m_to_400m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.gen/sources_1/ip/mmcm_50m_to_400m/mmcm_50m_to_400m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m_to_400m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
