webtalk_init -webtalk_dir D:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.sim/sim_1/behav/xsim/xsim.dir/tb_tdc_v5_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 26 11:17:48 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a6913b67-00f7-4642-bd47-abb54d436350" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a277e2ec01294283b114668a9a0e4637" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "17" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1162 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "38 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "481" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "31" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.75_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "167556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 5423259 -regid "" -xml D:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.sim/sim_1/behav/xsim/xsim.dir/tb_tdc_v5_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.sim/sim_1/behav/xsim/xsim.dir/tb_tdc_v5_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/01-Codes/XilinxCode/Vernier_tdc/v5_direct_sampling_tdc/prj/v5_direct_sampling_tdc.sim/sim_1/behav/xsim/xsim.dir/tb_tdc_v5_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
