# # =========================================================
# # TDC Fine Counter 核心物理约束与时序豁免文件
# # =========================================================

# # ---------------------------------------------------------
# # 1. 保护核心逻辑不被优化掉 (DONT_TOUCH)
# # ---------------------------------------------------------
# # 保护 CARRY4 原语本身
# set_property DONT_TOUCH true [get_cells -hierarchical *carry4_rising_inst*]
# set_property DONT_TOUCH true [get_cells -hierarchical *carry4_falling_inst*]

# # 保护延迟链抽头和专用级联线 (注意：已根据最新代码修改为 carry_cascade)
# set_property DONT_TOUCH true [get_nets -hierarchical *carry_cascade_a*]
# set_property DONT_TOUCH true [get_nets -hierarchical *carry_cascade_b*]
# set_property DONT_TOUCH true [get_nets -hierarchical *delay_chain_a*]
# set_property DONT_TOUCH true [get_nets -hierarchical *delay_chain_b*]

# # ---------------------------------------------------------
# # 2. 异步时序豁免 (FALSE PATH) - 防止 Vivado 乱牵红线
# # ---------------------------------------------------------
# # 豁免 PWM 异步输入路径
# set_false_path -from [get_ports pwm_signal]

# # 豁免从 CARRY4 进位输出 (CO) 到采样寄存器 (D端) 的纯异步跨时钟路径
# set_false_path -from [get_pins -hierarchical *carry4_rising_inst/CO[*]] -to [get_pins -hierarchical *sampled_chain_a_reg[*]/D]
# set_false_path -from [get_pins -hierarchical *carry4_falling_inst/CO[*]] -to [get_pins -hierarchical *sampled_chain_b_reg[*]/D]

# # ---------------------------------------------------------
# # 3. 物理位置约束 (PBLOCK) - TDC 的灵魂，保证皮秒级线性度
# # ---------------------------------------------------------
# # 锁定上升沿延迟链 (强制把 CARRY4 和 采样触发器 框在同一个区域内)
# create_pblock PBLOCK_TDC_RISE
# add_cells_to_pblock [get_pblocks PBLOCK_TDC_RISE] [get_cells -hierarchical *rising_delay_chain*]
# add_cells_to_pblock [get_pblocks PBLOCK_TDC_RISE] [get_cells -hierarchical *sampled_chain_a_reg*]
# # 注意：你需要自己去 Device 视图找一列空的 20 个 Slice 填在这里
# resize_pblock [get_pblocks PBLOCK_TDC_RISE] -add {SLICE_X1Y0:SLICE_X1Y19}

# # 锁定下降沿延迟链 (紧挨着上升沿放旁边另一列)
# create_pblock PBLOCK_TDC_FALL
# add_cells_to_pblock [get_pblocks PBLOCK_TDC_FALL] [get_cells -hierarchical *falling_delay_chain*]
# add_cells_to_pblock [get_pblocks PBLOCK_TDC_FALL] [get_cells -hierarchical *sampled_chain_b_reg*]
# resize_pblock [get_pblocks PBLOCK_TDC_FALL] -add {SLICE_X2Y0:SLICE_X2Y19}

# # ---------------------------------------------------------
# # 4. 系统时钟与 IO 管脚约束 (假设作用于顶层模块)
# # ---------------------------------------------------------
# # 定义 50MHz 板载主时钟
# create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

# # 引脚绑定 (根据你的开发板原理图)
# set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS15} [get_ports sys_clk]
# set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS15} [get_ports rst_n]
# set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports pwm_signal]
# set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS15} [get_ports valid_out]

# =========================================================
# TDC Fine Counter 核心物理约束与时序豁免文件 (修复版)
# =========================================================

# ---------------------------------------------------------
# 1. 保护 CARRY4 原语本身不被优化
# ---------------------------------------------------------
set_property DONT_TOUCH true [get_cells -hierarchical -filter {REF_NAME == CARRY4 && NAME =~ *carry4_rising_inst*}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {REF_NAME == CARRY4 && NAME =~ *carry4_falling_inst*}]

# (注意：线网的 DONT_TOUCH 已经转移到 Verilog 的 keep 属性中了，这里删除了)

# ---------------------------------------------------------
# 2. 异步时序豁免 (FALSE PATH) - 终极无死角语法
# ---------------------------------------------------------
# 豁免外部 PWM 异步输入
set_false_path -from [get_ports pwm_signal]

# 【核心修复】：不指定无效的起点，直接宣告“所有终点在这组采样寄存器上的路径，全都不看时序！”
# 这完美契合了 TDC 的异步采样本质。
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg*}]
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg*}]

# ---------------------------------------------------------
# 3. 物理位置约束 (PBLOCK)
# ---------------------------------------------------------
# 锁定上升沿延迟链

# 锁定下降沿延迟链

# 定义 50MHz 板载主时钟
#create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

# 引脚绑定 (根据你的开发板原理图)
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS15} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS15} [get_ports sys_rst_n]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports pwm_signal]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS15} [get_ports valid_out]


set_property BEL AFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[0]*}]
set_property BEL BFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[1]*}]
set_property BEL CFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[2]*}]
set_property BEL DFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[3]*}]
set_property LOC SLICE_X0Y0 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[0]*carry4*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[0]*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[1]*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[2]*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[3]*}]
set_property BEL AFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[4]*}]
set_property BEL BFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[5]*}]
set_property BEL CFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[6]*}]
set_property BEL DFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[7]*}]
set_property LOC SLICE_X0Y1 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[1]*carry4*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[4]*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[5]*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[6]*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[7]*}]
set_property BEL AFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[0]*}]
set_property BEL BFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[1]*}]
set_property BEL CFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[2]*}]
set_property BEL DFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[3]*}]
set_property LOC SLICE_X0Y0 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[0]*carry4*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[0]*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[1]*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[2]*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[3]*}]
set_property BEL AFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[4]*}]
set_property BEL BFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[5]*}]
set_property BEL CFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[6]*}]
set_property BEL DFF [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[7]*}]
set_property LOC SLICE_X0Y1 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[1]*carry4*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[4]*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[5]*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[6]*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[7]*}]
set_property LOC SLICE_X0Y0 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[0]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[0]}]
set_property -dict {LOC SLICE_X1Y0 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[0]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[1]}]
set_property -dict {LOC SLICE_X1Y0 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[1]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[2]}]
set_property -dict {LOC SLICE_X1Y0 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[2]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[3]}]
set_property -dict {LOC SLICE_X1Y0 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[3]*}]
set_property LOC SLICE_X0Y1 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[1]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[4]}]
set_property -dict {LOC SLICE_X1Y1 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[4]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[5]}]
set_property -dict {LOC SLICE_X1Y1 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[5]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[6]}]
set_property -dict {LOC SLICE_X1Y1 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[6]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[7]}]
set_property -dict {LOC SLICE_X1Y1 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[7]*}]
set_property LOC SLICE_X0Y2 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[2]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[8]}]
set_property -dict {LOC SLICE_X1Y2 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[8]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[9]}]
set_property -dict {LOC SLICE_X1Y2 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[9]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[10]}]
set_property -dict {LOC SLICE_X1Y2 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[10]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[11]}]
set_property -dict {LOC SLICE_X1Y2 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[11]*}]
set_property LOC SLICE_X0Y3 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[3]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[12]}]
set_property -dict {LOC SLICE_X1Y3 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[12]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[13]}]
set_property -dict {LOC SLICE_X1Y3 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[13]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[14]}]
set_property -dict {LOC SLICE_X1Y3 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[14]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[15]}]
set_property -dict {LOC SLICE_X1Y3 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[15]*}]
set_property LOC SLICE_X0Y4 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[4]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[16]}]
set_property -dict {LOC SLICE_X1Y4 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[16]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[17]}]
set_property -dict {LOC SLICE_X1Y4 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[17]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[18]}]
set_property -dict {LOC SLICE_X1Y4 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[18]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[19]}]
set_property -dict {LOC SLICE_X1Y4 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[19]*}]
set_property LOC SLICE_X0Y5 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[5]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[20]}]
set_property -dict {LOC SLICE_X1Y5 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[20]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[21]}]
set_property -dict {LOC SLICE_X1Y5 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[21]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[22]}]
set_property -dict {LOC SLICE_X1Y5 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[22]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[23]}]
set_property -dict {LOC SLICE_X1Y5 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[23]*}]
set_property LOC SLICE_X0Y6 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[6]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[24]}]
set_property -dict {LOC SLICE_X1Y6 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[24]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[25]}]
set_property -dict {LOC SLICE_X1Y6 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[25]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[26]}]
set_property -dict {LOC SLICE_X1Y6 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[26]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[27]}]
set_property -dict {LOC SLICE_X1Y6 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[27]*}]
set_property LOC SLICE_X0Y7 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[7]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[28]}]
set_property -dict {LOC SLICE_X1Y7 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[28]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[29]}]
set_property -dict {LOC SLICE_X1Y7 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[29]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[30]}]
set_property -dict {LOC SLICE_X1Y7 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[30]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[31]}]
set_property -dict {LOC SLICE_X1Y7 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[31]*}]
set_property LOC SLICE_X0Y8 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[8]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[32]}]
set_property -dict {LOC SLICE_X1Y8 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[32]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[33]}]
set_property -dict {LOC SLICE_X1Y8 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[33]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[34]}]
set_property -dict {LOC SLICE_X1Y8 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[34]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[35]}]
set_property -dict {LOC SLICE_X1Y8 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[35]*}]
set_property LOC SLICE_X0Y9 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[9]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[36]}]
set_property -dict {LOC SLICE_X1Y9 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[36]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[37]}]
set_property -dict {LOC SLICE_X1Y9 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[37]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[38]}]
set_property -dict {LOC SLICE_X1Y9 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[38]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[39]}]
set_property -dict {LOC SLICE_X1Y9 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[39]*}]
set_property LOC SLICE_X0Y10 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[10]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[40]}]
set_property -dict {LOC SLICE_X1Y10 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[40]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[41]}]
set_property -dict {LOC SLICE_X1Y10 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[41]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[42]}]
set_property -dict {LOC SLICE_X1Y10 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[42]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[43]}]
set_property -dict {LOC SLICE_X1Y10 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[43]*}]
set_property LOC SLICE_X0Y11 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[11]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[44]}]
set_property -dict {LOC SLICE_X1Y11 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[44]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[45]}]
set_property -dict {LOC SLICE_X1Y11 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[45]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[46]}]
set_property -dict {LOC SLICE_X1Y11 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[46]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[47]}]
set_property -dict {LOC SLICE_X1Y11 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[47]*}]
set_property LOC SLICE_X0Y12 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[12]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[48]}]
set_property -dict {LOC SLICE_X1Y12 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[48]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[49]}]
set_property -dict {LOC SLICE_X1Y12 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[49]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[50]}]
set_property -dict {LOC SLICE_X1Y12 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[50]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[51]}]
set_property -dict {LOC SLICE_X1Y12 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[51]*}]
set_property LOC SLICE_X0Y13 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[13]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[52]}]
set_property -dict {LOC SLICE_X1Y13 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[52]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[53]}]
set_property -dict {LOC SLICE_X1Y13 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[53]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[54]}]
set_property -dict {LOC SLICE_X1Y13 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[54]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[55]}]
set_property -dict {LOC SLICE_X1Y13 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[55]*}]
set_property LOC SLICE_X0Y14 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[14]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[56]}]
set_property -dict {LOC SLICE_X1Y14 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[56]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[57]}]
set_property -dict {LOC SLICE_X1Y14 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[57]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[58]}]
set_property -dict {LOC SLICE_X1Y14 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[58]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[59]}]
set_property -dict {LOC SLICE_X1Y14 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[59]*}]
set_property LOC SLICE_X0Y15 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[15]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[60]}]
set_property -dict {LOC SLICE_X1Y15 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[60]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[61]}]
set_property -dict {LOC SLICE_X1Y15 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[61]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[62]}]
set_property -dict {LOC SLICE_X1Y15 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[62]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[63]}]
set_property -dict {LOC SLICE_X1Y15 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[63]*}]
set_property LOC SLICE_X0Y16 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[16]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[64]}]
set_property -dict {LOC SLICE_X1Y16 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[64]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[65]}]
set_property -dict {LOC SLICE_X1Y16 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[65]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[66]}]
set_property -dict {LOC SLICE_X1Y16 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[66]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[67]}]
set_property -dict {LOC SLICE_X1Y16 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[67]*}]
set_property LOC SLICE_X0Y17 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[17]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[68]}]
set_property -dict {LOC SLICE_X1Y17 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[68]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[69]}]
set_property -dict {LOC SLICE_X1Y17 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[69]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[70]}]
set_property -dict {LOC SLICE_X1Y17 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[70]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[71]}]
set_property -dict {LOC SLICE_X1Y17 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[71]*}]
set_property LOC SLICE_X0Y18 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[18]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[72]}]
set_property -dict {LOC SLICE_X1Y18 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[72]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[73]}]
set_property -dict {LOC SLICE_X1Y18 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[73]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[74]}]
set_property -dict {LOC SLICE_X1Y18 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[74]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[75]}]
set_property -dict {LOC SLICE_X1Y18 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[75]*}]
set_property LOC SLICE_X0Y19 [get_cells -hierarchical -filter {NAME =~ *rising_delay_chain[19]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_a_reg[76]}]
set_property -dict {LOC SLICE_X1Y19 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[76]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_a_reg[77]}]
set_property -dict {LOC SLICE_X1Y19 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[77]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_a_reg[78]}]
set_property -dict {LOC SLICE_X1Y19 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[78]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_a_reg[79]}]
set_property -dict {LOC SLICE_X1Y19 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_a_reg[79]*}]
set_property LOC SLICE_X2Y0 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[0]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[0]}]
set_property -dict {LOC SLICE_X3Y0 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[0]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[1]}]
set_property -dict {LOC SLICE_X3Y0 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[1]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[2]}]
set_property -dict {LOC SLICE_X3Y0 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[2]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[3]}]
set_property -dict {LOC SLICE_X3Y0 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[3]*}]
set_property LOC SLICE_X2Y1 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[1]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[4]}]
set_property -dict {LOC SLICE_X3Y1 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[4]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[5]}]
set_property -dict {LOC SLICE_X3Y1 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[5]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[6]}]
set_property -dict {LOC SLICE_X3Y1 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[6]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[7]}]
set_property -dict {LOC SLICE_X3Y1 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[7]*}]
set_property LOC SLICE_X2Y2 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[2]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[8]}]
set_property -dict {LOC SLICE_X3Y2 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[8]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[9]}]
set_property -dict {LOC SLICE_X3Y2 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[9]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[10]}]
set_property -dict {LOC SLICE_X3Y2 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[10]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[11]}]
set_property -dict {LOC SLICE_X3Y2 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[11]*}]
set_property LOC SLICE_X2Y3 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[3]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[12]}]
set_property -dict {LOC SLICE_X3Y3 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[12]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[13]}]
set_property -dict {LOC SLICE_X3Y3 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[13]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[14]}]
set_property -dict {LOC SLICE_X3Y3 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[14]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[15]}]
set_property -dict {LOC SLICE_X3Y3 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[15]*}]
set_property LOC SLICE_X2Y4 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[4]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[16]}]
set_property -dict {LOC SLICE_X3Y4 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[16]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[17]}]
set_property -dict {LOC SLICE_X3Y4 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[17]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[18]}]
set_property -dict {LOC SLICE_X3Y4 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[18]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[19]}]
set_property -dict {LOC SLICE_X3Y4 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[19]*}]
set_property LOC SLICE_X2Y5 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[5]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[20]}]
set_property -dict {LOC SLICE_X3Y5 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[20]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[21]}]
set_property -dict {LOC SLICE_X3Y5 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[21]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[22]}]
set_property -dict {LOC SLICE_X3Y5 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[22]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[23]}]
set_property -dict {LOC SLICE_X3Y5 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[23]*}]
set_property LOC SLICE_X2Y6 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[6]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[24]}]
set_property -dict {LOC SLICE_X3Y6 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[24]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[25]}]
set_property -dict {LOC SLICE_X3Y6 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[25]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[26]}]
set_property -dict {LOC SLICE_X3Y6 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[26]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[27]}]
set_property -dict {LOC SLICE_X3Y6 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[27]*}]
set_property LOC SLICE_X2Y7 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[7]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[28]}]
set_property -dict {LOC SLICE_X3Y7 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[28]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[29]}]
set_property -dict {LOC SLICE_X3Y7 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[29]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[30]}]
set_property -dict {LOC SLICE_X3Y7 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[30]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[31]}]
set_property -dict {LOC SLICE_X3Y7 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[31]*}]
set_property LOC SLICE_X2Y8 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[8]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[32]}]
set_property -dict {LOC SLICE_X3Y8 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[32]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[33]}]
set_property -dict {LOC SLICE_X3Y8 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[33]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[34]}]
set_property -dict {LOC SLICE_X3Y8 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[34]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[35]}]
set_property -dict {LOC SLICE_X3Y8 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[35]*}]
set_property LOC SLICE_X2Y9 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[9]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[36]}]
set_property -dict {LOC SLICE_X3Y9 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[36]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[37]}]
set_property -dict {LOC SLICE_X3Y9 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[37]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[38]}]
set_property -dict {LOC SLICE_X3Y9 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[38]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[39]}]
set_property -dict {LOC SLICE_X3Y9 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[39]*}]
set_property LOC SLICE_X2Y10 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[10]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[40]}]
set_property -dict {LOC SLICE_X3Y10 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[40]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[41]}]
set_property -dict {LOC SLICE_X3Y10 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[41]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[42]}]
set_property -dict {LOC SLICE_X3Y10 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[42]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[43]}]
set_property -dict {LOC SLICE_X3Y10 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[43]*}]
set_property LOC SLICE_X2Y11 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[11]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[44]}]
set_property -dict {LOC SLICE_X3Y11 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[44]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[45]}]
set_property -dict {LOC SLICE_X3Y11 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[45]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[46]}]
set_property -dict {LOC SLICE_X3Y11 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[46]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[47]}]
set_property -dict {LOC SLICE_X3Y11 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[47]*}]
set_property LOC SLICE_X2Y12 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[12]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[48]}]
set_property -dict {LOC SLICE_X3Y12 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[48]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[49]}]
set_property -dict {LOC SLICE_X3Y12 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[49]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[50]}]
set_property -dict {LOC SLICE_X3Y12 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[50]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[51]}]
set_property -dict {LOC SLICE_X3Y12 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[51]*}]
set_property LOC SLICE_X2Y13 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[13]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[52]}]
set_property -dict {LOC SLICE_X3Y13 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[52]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[53]}]
set_property -dict {LOC SLICE_X3Y13 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[53]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[54]}]
set_property -dict {LOC SLICE_X3Y13 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[54]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[55]}]
set_property -dict {LOC SLICE_X3Y13 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[55]*}]
set_property LOC SLICE_X2Y14 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[14]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[56]}]
set_property -dict {LOC SLICE_X3Y14 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[56]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[57]}]
set_property -dict {LOC SLICE_X3Y14 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[57]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[58]}]
set_property -dict {LOC SLICE_X3Y14 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[58]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[59]}]
set_property -dict {LOC SLICE_X3Y14 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[59]*}]
set_property LOC SLICE_X2Y15 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[15]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[60]}]
set_property -dict {LOC SLICE_X3Y15 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[60]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[61]}]
set_property -dict {LOC SLICE_X3Y15 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[61]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[62]}]
set_property -dict {LOC SLICE_X3Y15 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[62]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[63]}]
set_property -dict {LOC SLICE_X3Y15 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[63]*}]
set_property LOC SLICE_X2Y16 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[16]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[64]}]
set_property -dict {LOC SLICE_X3Y16 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[64]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[65]}]
set_property -dict {LOC SLICE_X3Y16 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[65]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[66]}]
set_property -dict {LOC SLICE_X3Y16 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[66]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[67]}]
set_property -dict {LOC SLICE_X3Y16 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[67]*}]
set_property LOC SLICE_X2Y17 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[17]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[68]}]
set_property -dict {LOC SLICE_X3Y17 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[68]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[69]}]
set_property -dict {LOC SLICE_X3Y17 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[69]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[70]}]
set_property -dict {LOC SLICE_X3Y17 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[70]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[71]}]
set_property -dict {LOC SLICE_X3Y17 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[71]*}]
set_property LOC SLICE_X2Y18 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[18]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[72]}]
set_property -dict {LOC SLICE_X3Y18 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[72]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[73]}]
set_property -dict {LOC SLICE_X3Y18 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[73]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[74]}]
set_property -dict {LOC SLICE_X3Y18 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[74]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[75]}]
set_property -dict {LOC SLICE_X3Y18 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[75]*}]
set_property LOC SLICE_X2Y19 [get_cells -hierarchical -filter {NAME =~ *falling_delay_chain[19]*carry4*}]
set_property BEL AFF [get_cells {u_fine_counter/sampled_chain_b_reg[76]}]
set_property -dict {LOC SLICE_X3Y19 BEL AFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[76]*}]
set_property BEL BFF [get_cells {u_fine_counter/sampled_chain_b_reg[77]}]
set_property -dict {LOC SLICE_X3Y19 BEL BFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[77]*}]
set_property BEL CFF [get_cells {u_fine_counter/sampled_chain_b_reg[78]}]
set_property -dict {LOC SLICE_X3Y19 BEL CFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[78]*}]
set_property BEL DFF [get_cells {u_fine_counter/sampled_chain_b_reg[79]}]
set_property -dict {LOC SLICE_X3Y19 BEL DFF} [get_cells -hierarchical -filter {NAME =~ *sampled_chain_b_reg[79]*}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_400m]
